version: '2' # Docker-Compose version 2
services: # containers
  web: # django
    build: . # use Dockerfile
    image: django_web:v1
    container_name: django_web_container
    command: bash -c "
        python3 manage.py collectstatic --no-input &&
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        gunicorn django_celery_redis_boilerplate.wsgi:application -b 0:8000"
    expose:
      - "8000"
    ports: # django port
     - "8000:8000"
    volumes: # django web 저장 volume
     - .:/web_app
     - ./config/gunicorn:/etc/systemd/system
  

  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./src:/src
        - ./config/nginx:/etc/nginx/conf.d
    depends_on:
        - web